CREATE TABLE city_terminals(
    id INT AUTO_INCREMENT PRIMARY KEY,
    city_name VARCHAR(50) NOT NULL,
    terminal_name VARCHAR(70) NOT NULL ,
    latitude DECIMAL(10,6) NOT NULL,
    longitude DECIMAL(10,6) NOT NULL
);

ALTER  TABLE  city_terminals AUTO_INCREMENT=1;
INSERT INTO city_terminals (CITY_NAME, TERMINAL_NAME, LATITUDE, LONGITUDE)VALUES  ("ADANA","ADANA OTOGAR",36.997147, 35.264223);
INSERT INTO city_terminals (CITY_NAME, TERMINAL_NAME, LATITUDE, LONGITUDE)VALUES  ("AFYON","AFYON OTOGAR",38.790069, 30.511315);
INSERT INTO city_terminals (CITY_NAME, TERMINAL_NAME, LATITUDE, LONGITUDE)VALUES  ("ADIYAMAN","ADIYAMAN OTOGAR",37.773517, 38.322680);

SELECT * FROM city_terminals;
